### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by AnupamS01**

### CODE REVIEW

**Comment by AnupamAS0x1** [comment]
Welcome to npm, anupmas!

To complete your npm sign up, and as an additional security measure, you are requested to enter the one-time password (OTP) provided in this email.

The OTP code is: 48930934

We are also recommending that you enable two-factor authentication (2FA) with a trusted device so you will not be asked for an OTP over email with each log in.

2FA is an extra layer of security used when logging into websites or apps. With 2FA, you have to log in with your username and password and provide another form of authentication that only you know or have access to. 2FA also protects package publishing. When you publish a package from the command line you will be prompted to provide a generated token in order to do so. Don’t worry, if you want to automate publishing in CI/CD you can use an Automation Token to allow for publishing via token only without 2FA. https://github.blog/changelog/2020-10-02-npm-automation-tokens/

To enable 2FA, please follow the instructions found here. https://docs.npmjs.com/configuring-two-factor-authentication

To create an automation token, please follow the instructions found here. https://docs.npmjs.com/creating-and-viewing-access-tokens

If you have any questions or concerns please feel free to reach out to the npm support team. https://www.npmjs.com/support

You’re receiving this email because you recently created an npm account. If this wasn’t you, please ignore this email.

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you are trying to log in to npm using your username and password. As an additional security measure you are requested to enter the OTP code (one-time password) provided in this email.

If you did not intend to log in to npm, please ignore this email.

The OTP code is: 63643222

If you enable two-factor authentication (2FA) with a trusted device you will not be asked for an OTP over email anymore.

2FA is an extra layer of security used when logging into websites or apps. With 2FA, you have to log in with your username and password and provide another form of authentication that only you know or have access to. 2FA also protects package publishing. When you publish a package from the command line you will be prompted to provide a generated token in order to do so. Don’t worry, if you want to automate publishing in CI/CD you can use an Automation Token to allow for publishing via token only without 2FA. https://github.blog/changelog/2020-10-02-npm-automation-tokens/

To enable 2FA, please follow the instructions found here. https://docs.npmjs.com/configuring-two-factor-authentication

To create an automation token, please follow the instructions found here. https://docs.npmjs.com/creating-and-viewing-access-tokens

If you have any questions or concerns please feel free to reach out to the npm support team. https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi anupmas!

You have been invited as a maintainer of the package react-native-transcribe. To accept the invitation, click the following link:

https://www.npmjs.com/verify/24bd8c27-e176-498d-8b0f-7f4e015533ea

This invitation will expire in one week.

If you have questions, you can contact us at https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi anupmas!

A new version of the package react-native-transcribe (1.2.0) was published at 2023-10-10T10:14:19.783Z from 103.160.107.118.
The shasum of this package is cb60ad6be7f4864911ccbad632c9b64a38fa1ea7.

If you have questions or security concerns, you can contact us at https://www.npmjs.com/support.

Thanks,

The npm team.

**Comment by AnupamAS0x1** [comment]
Hi anupmas!

A new version of the package react-native-transcribe (1.3.0) was published at 2023-10-10T10:38:48.185Z from 103.160.107.118.
The shasum of this package is 61742cfde62cadd8a068d13c81569f118f504907.

If you have questions or security concerns, you can contact us at https://www.npmjs.com/support.

Thanks,

The npm team.

**Comment by AnupamAS0x1** [comment]
Hi anupmas!

A new version of the package react-native-transcribe (1.4.0) was published at 2023-10-10T11:53:47.540Z from 103.160.107.118.
The shasum of this package is c7a4c18996e437f64b264054fb3180996c2442bb.

If you have questions or security concerns, you can contact us at https://www.npmjs.com/support.

Thanks,

The npm team.

**Comment by AnupamS01** [comment]
sd

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Comment by AnupamAS0x1** [comment]
Hi, anupmas!

It looks like you still do not have two-factor authentication (2FA) enabled on your npm account.

To enable 2FA, please follow instructions in our documentation under "Configuring two-factor authentication". Link: https://docs.npmjs.com/configuring-two-factor-authentication

**What is 2FA?**
2FA is an extra layer of security used when logging in to websites or apps. With 2FA, you must log in with your username/password and provide another form of authentication that only you know or have access to. 

2FA also protects package publishing. When you publish a package from the command line, you will be prompted to provide a generated token to do so. 

You can read more about the importance of 2FA here. Link: https://docs.npmjs.com/about-two-factor-authentication

**What if I lose my 2FA device?**
npm provides several options to avoid account lockout and for account recovery in the case of lost 2FA devices.
- Ensure you store your recovery codes in a safe place, each recovery code can be used once to gain access to your account. This is by far the easiest way to get access when locked out. Link: https://docs.npmjs.com/recovering-your-2fa-enabled-account#viewing-and-regenerating-recovery-code
- Register multiple security keys to ensure that even if you lose access to one of your devices you will not be locked out.
- Link your GitHub and Twitter accounts to npm which can be used for identity verification if you do need to ever go through account recovery. Link: https://docs.npmjs.com/managing-your-profile-settings#linking-your-npm-and-github-accounts

**Will enabling 2FA impact my CI/CD workflows?**
Don’t worry, if you want to automate publishing in CI/CD, you can use a granular access token to publish without 2FA. To create a granular access token, please follow our documentation under "Creating granular access tokens". Link: https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website

If you have any questions or concerns, please feel free to reach out to the npm support team. Link: https://www.npmjs.com/support

Thanks,
The npm team

**Pull request closed without merging**
